version: '3.9'
services:
  db:
    image: mongo:4.2
    restart: always
    container_name: todo-list_mongodb
    environment:
      MONGO_TNITDB_ROOT_USERNAME: ${DB_USER}
      MONGO INITDB ROOT PASSWORD: ${DB_PASSWORD}
    ports:
      - ${DB_PORT}: 27017
    volumes:
      - todo-list:/data/db
  do_ui:
    image: mongo-express:1.0.2-20
    restart: always
    container name: todo-list mongo express
    ports:
      - 8081:8081
    environment:
    ME_CONFIG_BASICAUTH_USERNAME: ${DB_USER}
    ME_CONFIG_BASICAUTH_PASSWORD: ${DB_PASSWORD}
    ME_CONFIG_MONGODB_ADMINUSERNAME: ${DB_USER}
    ME_CONFIG_MONGODB_ADMINPASSWORD: ${DB_PASSWORD}
    ME_CONFIG_MONGODE_URL: mongodb://${DB_USER}:${DB_PASSWORD}@db:${DR_PORT}/
volumes:
  todo-List: